version: '3.1'
services:
  reverse_proxy:
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/Caddyfile:/Caddyfile:ro
    ports:
      - "5544:80"

  frontend:
    build: ./frontend
    restart: always
    expose:
      - "8000"

  backend:
    build: ./backend
    restart: always
    command: --redis-host=cache
    depends_on:
      - cache
    expose:
      - "8080"

  cache:
    image: redis
    restart: always
    expose:
      - "6379"
